---
- name: 'Install Python PIP'
  tags: 'aws-cli'
  sudo: 'yes'
  apt: >
    pkg=python-pip
    state=latest

- name: 'Install AWS CLI'
  tags: 'aws-cli'
  sudo: 'yes'
  pip: >
    name=awscli
    state=latest

- name: Set home directory of the user
  set_fact:
    home_dir: /home/{{ aws_cli_user }}
  when: "not \"{{ aws_cli_user }}\" == \"root\""

- name: Set home directory for root
  set_fact:
    home_dir: /root
  when: "\"{{ aws_cli_user }}\" == \"root\""

- name: 'Create the AWS config directory'
  tags: 'aws-cli'
  sudo: 'yes'
  file: >
    path={{ home_dir }}/.aws
    state=directory
    owner={{ aws_cli_user }}
    group={{ aws_cli_user }}
    mode=0755

- name: 'Copy AWS CLI config'
  tags: 'aws-cli'
  sudo: 'yes'
  template: >
    src=aws_cli_config.j2
    dest={{ home_dir }}/.aws/config
    owner={{ aws_cli_user }}
    group={{ aws_cli_user }}
    mode=0600
